#!/usr/bin/env python3
# Generates scripts/rk-symbol-registry.txt: the single-module isolation word list.
# Top-level type names declared inside Packages/RemoteKit/Sources (wired files).
# Names that ALSO exist as top-level declarations in app sources are excluded as
# ambiguous (the merge build already proves app-side uses of those are pre-existing).
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RKSRC = os.path.join(ROOT, "Packages/RemoteKit/Sources")
APPSRC = os.path.join(ROOT, "src/ios")
DECL = re.compile(r'^(?:public\s+|internal\s+|final\s+|actor\s+)*(?:class|struct|enum|protocol|actor)\s+([A-Za-z_]\w*)', re.M)
INDENT_ATTR = re.compile(r'^\s*@(?:MainActor|Observable|Sendable|available)\b[^\n]*\n((?:public|internal|final|actor|\s)*)\b(class|struct|enum|protocol|actor)\s+([A-Za-z_]\w*)', re.M)

def decls_in(paths):
    out = set()
    for p in paths:
        try:
            s = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        out |= set(DECL.findall(s))
        out |= {m.group(3) for m in INDENT_ATTR.finditer(s)}
    return out

def swift_files(base, skip=None):
    res = []
    for root, dirs, fs in os.walk(base):
        dirs[:] = [d for d in dirs if d not in (".git", "Minis.xcodeproj", "Generated")]
        if skip and any(x in root for x in skip):
            continue
        res += [os.path.join(root, f) for f in fs if f.endswith(".swift")]
    return res

rk = decls_in(swift_files(RKSRC))
# drop our own glue facade duplicates is NOT wanted: facades must stay in the list
app = decls_in(swift_files(APPSRC, skip=["Views/ModeTabs", "Views/AuthAA"]))
ambiguous = sorted(n for n in rk if n in app)
registry = sorted(rk - app)
out = os.path.join(ROOT, "scripts/rk-symbol-registry.txt")
with open(out, "w") as f:
    f.write("# GENERATED by scripts/gen_rk_registry.py — do not hand-edit.\n")
    f.write("# Single-module isolation word list (D4 gate-1, 2026-09-15 B-plan).\n")
    f.write("# App code outside RemoteKit dirs and registered seams must not reference these.\n")
    f.write("# Ambiguous names (also top-level in app sources, merge-verified) excluded: see --report.\n")
    for n in registry:
        f.write(n + "\n")
if "--report" in sys.argv:
    print(f"registry={len(registry)} excluded_ambiguous={len(ambiguous)}")
    print("ambiguous:", ", ".join(ambiguous) if ambiguous else "-")
print(f"[gen] wrote {out}: {len(registry)} symbols")
