#!/usr/bin/env python3
# Generates scripts/rk-symbol-registry.txt: the single-module isolation word list.
# Top-level type names declared inside Packages/RemoteKit/Sources (wired files).
# Names that ALSO exist as top-level declarations in app sources are excluded as
# ambiguous (the merge build already proves app-side uses of those are pre-existing).
#
# Modes (BATCH-B 2026-09-22):
#   (default)   regenerate and OVERWRITE scripts/rk-symbol-registry.txt
#   --check     READ-ONLY freshness gate: recompute, compare with the committed file,
#               print a diff summary, exit 1 on any drift, exit 2 if the committed file
#               is missing/unreadable. Writes nothing — safe to run in CI.
#               Rationale: the word list is generated, so a stale list is a silent
#               hole in import-scan.sh's deep mode (it was 101 symbols behind on
#               2026-09-22, incl. ComposerDraft / V2WorkspaceEntry, both in use).
#   --report    also print the excluded-ambiguous set
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RKSRC = os.path.join(ROOT, "Packages/RemoteKit/Sources")
APPSRC = os.path.join(ROOT, "src/ios")
DECL = re.compile(r'^(?!private|fileprivate)(?:(?:public|internal|final|actor|nonisolated|remote|indirect)\s+)*(?:class|struct|enum|protocol|actor)\s+([A-Za-z_]\w*)', re.M)
INDENT_ATTR = re.compile(r'^\s*@(?:MainActor|Observable|Sendable|available)\b[^\n]*\n((?:public|internal|final|actor|\s)*)\b(class|struct|enum|protocol|actor)\s+([A-Za-z_]\w*)', re.M)

def decls_in(paths):
    out = set()
    for p in paths:
        try:
            s = open(p, encoding="utf-8", errors="ignore").read()
        except OSError as e:
            # A silently skipped file is a hole in the word list (its symbols never get
            # enforced). Collect and let the caller fail-closed. [BATCH-B 2026-09-22]
            UNREADABLE.append(f"{p}: {e}")
            continue
        out |= set(DECL.findall(s))
        out |= {m.group(3) for m in INDENT_ATTR.finditer(s)}
    return out

UNREADABLE = []

def wired_files():
    # Single source of truth = Package.swift sources whitelist (same ledger the
    # pbxproj transform reads). Unwired frozen files are not compiled anywhere:
    # their private/colliding names must not pollute the gate word list.
    try:
        man = open(os.path.join(RKSRC, "..", "Package.swift")).read()
    except OSError as e:
        print(f"[gen] FATAL: cannot read Package.swift wiring ledger: {e} — refusing to emit a word list", file=sys.stderr)
        sys.exit(2)
    sm = re.search(r'sources:\s*\[(.*?)\]', man, re.S)
    if not sm:
        print("[gen] FATAL: no `sources: [...]` ledger in Package.swift — refusing to emit a word list", file=sys.stderr)
        sys.exit(2)
    res = []
    for e in re.findall(r'"([^"]+)"', sm.group(1)):
        if e.endswith(".md"):
            continue
        path = os.path.join(RKSRC, e)
        if os.path.isdir(path):
            for root, _d, fs in os.walk(path):
                res += [os.path.join(root, f) for f in sorted(fs) if f.endswith(".swift")]
        elif path.endswith(".swift"):
            res.append(path)
    return res


def swift_files(base, skip=None):
    res = []
    for root, dirs, fs in os.walk(base):
        dirs[:] = [d for d in dirs if d not in (".git", "Minis.xcodeproj", "Generated")]
        if skip and any(x in root for x in skip):
            continue
        res += [os.path.join(root, f) for f in fs if f.endswith(".swift")]
    return res

rk = decls_in(wired_files())
# drop our own glue facade duplicates is NOT wanted: facades must stay in the list
app = decls_in(swift_files(APPSRC, skip=["Views/ModeTabs", "Views/AuthAA"]))
ambiguous = sorted(n for n in rk if n in app)
registry = sorted(rk - app)
if UNREADABLE:
    print("[gen] FATAL: source files the word list could not read (fail-closed, nothing written):", file=sys.stderr)
    for u in UNREADABLE[:20]:
        print(f"  {u}", file=sys.stderr)
    sys.exit(2)
if not rk:
    print("[gen] FATAL: 0 RemoteKit declarations found — wiring ledger or scan paths are broken", file=sys.stderr)
    sys.exit(2)
out = os.path.join(ROOT, "scripts/rk-symbol-registry.txt")
text = (
    "# GENERATED by scripts/gen_rk_registry.py — do not hand-edit.\n"
    "# Single-module isolation word list (D4 gate-1, 2026-09-15 B-plan).\n"
    "# App code outside RemoteKit dirs and registered seams must not reference these.\n"
    "# Ambiguous names (also top-level in app sources, merge-verified) excluded: see --report.\n"
    + "".join(n + "\n" for n in registry)
)
if "--check" in sys.argv:
    try:
        have = open(out, encoding="utf-8").read()
    except OSError as e:
        print(f"[gen --check] FATAL: cannot read {out}: {e} — gate is fail-closed", file=sys.stderr)
        sys.exit(2)
    have_set = {l for l in have.splitlines() if l and not l.startswith("#")}
    new_set = set(registry)
    added, removed = sorted(new_set - have_set), sorted(have_set - new_set)
    print(f"[gen --check] committed={len(have_set)} regenerated={len(new_set)} "
          f"missing_from_committed={len(added)} stale_in_committed={len(removed)}")
    if added or removed:
        if added:
            print("  symbols the gate is NOT enforcing (declared in RemoteKit, absent from the list):")
            for n in added[:25]:
                print(f"    + {n}")
            if len(added) > 25:
                print(f"    ... {len(added) - 25} more")
        if removed:
            print("  symbols no longer declared in RemoteKit (list needs a refresh):")
            for n in removed[:25]:
                print(f"    - {n}")
            if len(removed) > 25:
                print(f"    ... {len(removed) - 25} more")
        print(f"[gen --check] DRIFT: {out} is not what {os.path.relpath(RKSRC, ROOT)} declares.")
        print("[gen --check] fix: python3 scripts/gen_rk_registry.py   (then review the diff — a")
        print("[gen --check]       refreshed list widens import-scan.sh deep-mode coverage.)")
        sys.exit(1)
    print("[gen --check] word list is fresh (read-only check, nothing written)")
    sys.exit(0)
with open(out, "w") as f:
    f.write(text)
if "--report" in sys.argv:
    print(f"registry={len(registry)} excluded_ambiguous={len(ambiguous)}")
    print("ambiguous:", ", ".join(ambiguous) if ambiguous else "-")
print(f"[gen] wrote {out}: {len(registry)} symbols")
